/**
 * Demo bookmarks for guests.
 *
 * Signing in as a guest used to land on an empty app, which reads as an unused
 * product. Every guest instead gets their own copy of a frozen set of real
 * bookmarks (data/demo/bookmarks.json, regenerated by
 * scripts/export-demo-bookmarks.mjs). Nothing is generated at sign-in time — the
 * tags and summaries were produced by the real pipeline and cached — so guests
 * cost nothing and see the app fully populated on first paint.
 *
 * The copies are deleted along with the guest account by cleanup_guest_data()
 * 24 hours after sign-in.
 */
import type { User } from "@supabase/supabase-js";
import type { createClient } from "@/lib/supabase/server";
import demoBookmarks from "../../data/demo/bookmarks.json";

type ServerSupabase = Awaited<ReturnType<typeof createClient>>;

const HOUR_MS = 60 * 60 * 1000;

/**
 * Inserts the demo set the first time an anonymous user reaches the app.
 *
 * Safe to call on every request: signed-in users return immediately, and a
 * guest who already has bookmarks costs one indexed lookup.
 *
 * Never throws — demo data is a nicety and must not be able to take the page
 * down with it.
 */
export async function ensureGuestDemoData(
  supabase: ServerSupabase,
  user: User
): Promise<void> {
  if (user.is_anonymous !== true) return;

  // Deliberately not filtered by is_trashed: a guest who moves everything to
  // the trash still counts as seeded, otherwise the next page load would put
  // the whole demo set back.
  const { data: existing, error: lookupError } = await supabase
    .from("bookmarks")
    .select("id")
    .eq("user_id", user.id)
    .limit(1);

  if (lookupError) {
    console.error("[guest-seed] lookup failed:", lookupError.message);
    return;
  }
  if (existing && existing.length > 0) return;

  const now = Date.now();
  const rows = demoBookmarks.map(({ addedHoursAgo, ...bookmark }) => ({
    ...bookmark,
    user_id: user.id,
    // The fixture stores offsets rather than dates so the list always looks
    // recently used, however long the demo sits there.
    created_at: new Date(now - addedHoursAgo * HOUR_MS).toISOString(),
    ai_status: "done",
  }));

  // Two page loads racing each other both see zero rows above, so the insert
  // itself has to be the guard: bookmarks has UNIQUE (user_id, video_id), and
  // ignoreDuplicates turns the second writer into ON CONFLICT DO NOTHING.
  const { error: insertError } = await supabase
    .from("bookmarks")
    .upsert(rows, { onConflict: "user_id,video_id", ignoreDuplicates: true });

  if (insertError) {
    console.error("[guest-seed] insert failed:", insertError.message);
  }
}
